# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 00:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    replaces = [('document_description_store', '0001_initial'), ('document_description_store', '0002_auto_20170211_1621'), ('document_description_store', '0003_documentmetadata_encryption_type'), ('document_description_store', '0004_remove_documentmetadata_uri')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secret_store', '0002_auto_20161005_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('encrypted_document_key', models.TextField()),
                ('encrypted_document_size', models.BigIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content_length', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=1000)),
                ('compressed', models.BooleanField(default=False)),
                ('encryption_type', models.CharField(default='AES|CBC', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='documentdescription',
            name='document_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_description_store.DocumentMetadata'),
        ),
        migrations.AddField(
            model_name='documentdescription',
            name='key_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret_store.KeyPair'),
        ),
        migrations.AlterModelOptions(
            name='documentdescription',
            options={'permissions': (('view_document_description', 'View Document Description'),)},
        ),
        migrations.AddField(
            model_name='documentdescription',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 11, 16, 21, 31, 52123, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
