# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_description_store', '0003_documentmetadata_encryption_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmetadata',
            name='uri',
        ),
    ]
