# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('secret_store', '0001_initial'), ('secret_store', '0002_auto_20161005_0709'), ('secret_store', '0003_auto_20161007_1918')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='keypair',
            name='private',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret_store.PrivateKey'),
        ),
        migrations.AddField(
            model_name='keypair',
            name='public',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret_store.PublicKey'),
        ),
    ]
